# Generated by Django 3.2 on 2025-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250319_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code_created_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
